# Generated by Django 3.0.7 on 2021-03-06 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import materials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('x_title', models.CharField(max_length=100)),
                ('x_unit', models.CharField(blank=True, max_length=20)),
                ('y_title', models.CharField(max_length=100)),
                ('y_unit', models.CharField(blank=True, max_length=20)),
                ('legend', models.CharField(blank=True, max_length=100)),
                ('line_counter', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_chart_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('formula', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_compound_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_compound_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_experimental', models.BooleanField()),
                ('sample_type', models.PositiveSmallIntegerField(choices=[(0, 'single crystal'), (1, 'powder'), (2, 'film'), (3, 'bulk polycrystalline'), (4, 'pellet'), (5, 'nanoform'), (6, 'unknown')])),
                ('crystal_system', models.PositiveSmallIntegerField(choices=[(0, 'triclinic'), (1, 'monoclinic'), (2, 'orthorhombic'), (3, 'tetragonal'), (4, 'trigonal'), (5, 'hexagonal'), (6, 'cubic'), (7, 'unknown')])),
                ('space_group', models.CharField(blank=True, max_length=20)),
                ('representative', models.BooleanField(default=False)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='materials.Compound')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_dataset_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'data sets',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('journal', models.CharField(blank=True, max_length=500)),
                ('vol', models.CharField(max_length=100)),
                ('pages_start', models.CharField(max_length=10)),
                ('pages_end', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('doi_isbn', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('input_data_file', models.FileField(null=True, upload_to=materials.models.data_file_path)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_subset_created_by', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsets', to='materials.Dataset')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_subset_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'data subsets',
            },
        ),
        migrations.CreateModel(
            name='ToleranceFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_source', models.PositiveSmallIntegerField(choices=[(0, 'Based on Shannon Radii'), (1, 'Experimental'), (2, 'Averaged')], default=0)),
                ('t_1', models.FloatField(blank=True, null=True)),
                ('t_4', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_tolerancefactor_created_by', to=settings.AUTH_USER_MODEL)),
                ('subset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolerance_factors', to='materials.Subset')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_tolerancefactor_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SynthesisMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('starting_materials', models.TextField(blank=True)),
                ('product', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_synthesismethod_created_by', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synthesis', to='materials.Dataset')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_synthesismethod_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_property_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_property_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='LatticeConstant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('c', models.FloatField()),
                ('alpha', models.FloatField()),
                ('beta', models.FloatField()),
                ('gamma', models.FloatField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_latticeconstant_created_by', to=settings.AUTH_USER_MODEL)),
                ('subset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lattice_constants', to='materials.Subset')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_latticeconstant_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FixedPropertyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.FloatField()),
                ('value_type', models.PositiveSmallIntegerField(choices=[(0, '='), (1, '≈'), (2, '>'), (3, '≥'), (4, '<'), (5, '≤')], default=0)),
                ('unit', models.CharField(max_length=20)),
                ('counter', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_fixedpropertyvalue_created_by', to=settings.AUTH_USER_MODEL)),
                ('fixed_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.Property')),
                ('subset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_values', to='materials.Subset')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_fixedpropertyvalue_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperimentalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_experimentaldetails_created_by', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimental', to='materials.Dataset')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_experimentaldetails_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'experimental details',
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='primary_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_property', to='materials.Property'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_dataset_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataset',
            name='verified_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('x_value', models.FloatField()),
                ('y_value', models.FloatField()),
                ('point_counter', models.PositiveSmallIntegerField(default=0)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='materials.Chart')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_datapoint_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_datapoint_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComputationalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.TextField(blank=True)),
                ('level_of_theory', models.TextField(blank=True)),
                ('xc_functional', models.TextField(blank=True)),
                ('k_point_grid', models.TextField(blank=True)),
                ('level_of_relativity', models.TextField(blank=True)),
                ('basis_set_definition', models.TextField(blank=True)),
                ('numerical_accuracy', models.TextField(blank=True)),
                ('external_url', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_computationaldetails_created_by', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computational', to='materials.Dataset')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_computationaldetails_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'computational details',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('computational_details', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.ComputationalDetails')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_comment_created_by', to=settings.AUTH_USER_MODEL)),
                ('experimental_details', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.ExperimentalDetails')),
                ('synthesis_method', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.SynthesisMethod')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_comment_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chart',
            name='subset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='materials.Subset'),
        ),
        migrations.AddField(
            model_name='chart',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_chart_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BondLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('element_a', models.CharField(max_length=20)),
                ('element_b', models.CharField(max_length=20)),
                ('r_avg', models.FloatField(blank=True, null=True)),
                ('r_shannon', models.FloatField(blank=True, null=True)),
                ('global_average', models.FloatField(blank=True, null=True)),
                ('ravg_rglobal', models.FloatField(blank=True, null=True)),
                ('ravg_rshannon', models.FloatField(blank=True, null=True)),
                ('bond_counter', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_bondlength_created_by', to=settings.AUTH_USER_MODEL)),
                ('subset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_length', to='materials.Subset')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_bondlength_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('institution', models.CharField(blank=True, max_length=600)),
                ('references', models.ManyToManyField(related_name='authors', to='materials.Reference')),
            ],
        ),
        migrations.CreateModel(
            name='AtomicCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('label', models.CharField(max_length=20)),
                ('coord_1', models.FloatField()),
                ('coord_2', models.FloatField()),
                ('coord_3', models.FloatField()),
                ('element', models.CharField(blank=True, max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_atomiccoordinate_created_by', to=settings.AUTH_USER_MODEL)),
                ('subset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atomic_coordinates', to='materials.Subset')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_atomiccoordinate_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdditionalFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('additional_file', models.FileField(upload_to=materials.models.additional_file_path)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_additionalfile_created_by', to=settings.AUTH_USER_MODEL)),
                ('subset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_files', to='materials.Subset')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_additionalfile_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
