# Generated by Django 3.0.7 on 2021-03-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_externalrepository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computationaldetails',
            name='external_url',
        ),
    ]
