# Generated by Django 3.0.7 on 2021-03-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_subset_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='line_counter',
            new_name='curve_counter',
        ),
    ]
