# Generated by Django 3.0.7 on 2021-03-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_auto_20210310_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latticeconstant',
            name='a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='latticeconstant',
            name='alpha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='latticeconstant',
            name='b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='latticeconstant',
            name='beta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='latticeconstant',
            name='c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='latticeconstant',
            name='gamma',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
