# Generated by Django 3.0.7 on 2021-03-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_auto_20210311_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latticeconstant',
            name='a',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='latticeconstant',
            name='alpha',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='latticeconstant',
            name='b',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='latticeconstant',
            name='beta',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='latticeconstant',
            name='c',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='latticeconstant',
            name='gamma',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
