# Generated by Django 3.0.7 on 2021-03-12 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_auto_20210311_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='materials.Compound'),
        ),
    ]
