# Generated by Django 3.0.7 on 2021-03-19 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0010_auto_20210318_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='shannonionicradii',
            name='element',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ShannonIonicRadiiRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('element', models.CharField(blank=True, max_length=20)),
                ('charge', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('coordination', models.CharField(blank=True, max_length=20)),
                ('ionic_radius', models.FloatField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_shannonionicradiiref_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_shannonionicradiiref_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('element', 'charge', 'coordination')},
            },
        ),
    ]
