# Generated by Django 3.0.7 on 2021-03-19 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_auto_20210319_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shannonionicradiiref',
            name='created',
        ),
        migrations.RemoveField(
            model_name='shannonionicradiiref',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='shannonionicradiiref',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='shannonionicradiiref',
            name='updated_by',
        ),
    ]
