# Generated by Django 3.0.7 on 2021-03-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_auto_20210319_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shannonionicradiiref',
            name='key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
