# Generated by Django 3.0.7 on 2021-03-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_auto_20210319_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='shannonionicradii',
            name='spin_state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'no spin'), (1, 'high spin'), (2, 'low spin')], default=0),
        ),
        migrations.AddField(
            model_name='shannonionicradiiref',
            name='spin_state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'no spin'), (1, 'high spin'), (2, 'low spin')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='shannonionicradiiref',
            unique_together={('element', 'charge', 'coordination', 'spin_state')},
        ),
    ]
