# Generated by Django 3.0.7 on 2021-03-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_auto_20210319_2148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShannonIonicRadiiRef',
            new_name='ShannonRadiiTable',
        ),
    ]
