# Generated by Django 3.0.7 on 2021-03-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0016_auto_20210320_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondlength',
            name='data_source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Experimental'), (2, 'Averaged')], default=1),
        ),
    ]
