# Generated by Django 3.0.7 on 2021-03-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0017_auto_20210321_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondlength',
            name='r_label',
            field=models.PositiveSmallIntegerField(choices=[(0, 'I-X'), (1, "II,I'-X"), (2, 'IV,V-X'), (3, 'NA')], default=3),
        ),
    ]
