# Generated by Django 3.0.7 on 2021-03-23 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0019_auto_20210323_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('r_label', models.PositiveSmallIntegerField(choices=[(0, 'I-X'), (1, "II,I'-X"), (2, 'IV,V-X')], default=0)),
                ('element_a', models.CharField(max_length=20)),
                ('element_b', models.CharField(max_length=20)),
                ('bond_id', models.CharField(blank=True, max_length=20)),
                ('r_exp', models.FloatField(blank=True, null=True)),
                ('r_avg', models.FloatField(blank=True, null=True)),
                ('r_shannon', models.FloatField(blank=True, null=True)),
                ('counter', models.PositiveSmallIntegerField(default=0)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_length', to='materials.Compound')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_bondlength_created_by', to=settings.AUTH_USER_MODEL)),
                ('subset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_length', to='materials.Subset')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_bondlength_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='experimentalbondlength',
            name='compound',
        ),
        migrations.RemoveField(
            model_name='experimentalbondlength',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='experimentalbondlength',
            name='subset',
        ),
        migrations.RemoveField(
            model_name='experimentalbondlength',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='AveragedBondLength',
        ),
        migrations.DeleteModel(
            name='ExperimentalBondLength',
        ),
    ]
