# Generated by Django 3.0.7 on 2021-03-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_auto_20210323_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bondlength',
            old_name='r_avg',
            new_name='averaged_r',
        ),
        migrations.RenameField(
            model_name='bondlength',
            old_name='r_exp',
            new_name='experimental_r',
        ),
        migrations.RenameField(
            model_name='bondlength',
            old_name='r_shannon',
            new_name='shannon_r',
        ),
    ]
