# Generated by Django 3.0.7 on 2021-03-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0021_auto_20210323_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shannonionicradii',
            name='charge',
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shannonradiitable',
            name='charge',
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
    ]
