# Generated by Django 3.0.7 on 2021-03-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0022_auto_20210323_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolerancefactor',
            name='space_group',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
