# Generated by Django 3.0.7 on 2021-03-27 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0023_tolerancefactor_space_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subset',
            options={},
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='representative',
        ),
        migrations.AddField(
            model_name='dataset',
            name='comments',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='compound',
            name='formula',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='primary_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='materials.Property'),
        ),
        migrations.CreateModel(
            name='SpaceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_spacegroup_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_spacegroup_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='dataset',
            name='space_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='materials.SpaceGroup'),
        ),
        migrations.AlterField(
            model_name='tolerancefactor',
            name='space_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolerance_factors', to='materials.SpaceGroup'),
        ),
    ]
