# Generated by Django 3.0.7 on 2021-03-31 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0025_auto_20210330_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='comments',
            new_name='update_comments',
        ),
    ]
