# Generated by Django 3.0.7 on 2021-04-07 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0028_auto_20210407_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='x_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chart',
            name='y_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experimentaldetails',
            name='method',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subset',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsets', to='materials.Reference'),
        ),
    ]
